export enum AgeGroupEnum {
    BELOW_FIFTEEN = 'Below 15',
    FIFTEEN_TO_NINETEEN = '15-19',
    TWENTY_TO_TWENTY_FOUR = '20-24',
    TWENTY_FIVE_TO_TWENTY_NINE = '25-29',
    THIRTY_TO_THIRTY_FOUR = '30-34',
    THIRTY_FIVE_TO_THIRTY_NINE = '35-39',
    FORTY_TO_FORTY_FOUR = '40-44',
    FORTY_FIVER_AND_UP = '45 & Up',
}
