export enum AppointmentTypeEnum {
    GENERAL = 'General',
    PRENATAL = 'Prenatal',
    DENTAL_CARE = 'Dental Care',
    CHILD_CARE = 'Child Care',
    CHILD_NUTRITION = 'Child Nutrition',
    INJURY = 'Injury',
    ADULT_IMMUNIZATION = 'Adult Immunization',
    POSTPARTUM = 'Postpartum',
    TUBERCULOSIS = 'Tuberculosis',
    CHILD_IMMUNIZATION = 'Child Immunization',
    SICK_CHILDREN = 'Sick Children',
    // FAMILY_PLANNING = 'Family Planning',
    // FIRECRACKER_INJURY = 'Firecracker Injury',
    ANIMAL_BITE = 'Animal Bite',
    MEDICO_LEGAL = 'Medico Legal',
}
